name: mpf

channels:
  - conda-forge
  - defaults

dependencies:
  - python == 3.9
  - pip
  # Core scientific python
  - numpy
  - scipy
  - astropy
  - specutils
  - dill
  
  # Plotting
  - matplotlib

  # Jupyter Environment
  - jupyterlab

  # Pip install
  - pip:
    - lmfit
    - dust_extinction